version: "3.9"

services: 
  rabbitmq:
    image: rabbitmq:3
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password

  windparkdemo:
    image: windparkdemo:latest
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - WindParkInterval:WindParkApiFrequencySeconds=10
      - WindParkInterval:WindParkAggregationFrequencyMinutes=1
      - RabbitMqSection:HostName=rabbitmq
      - RabbitMqSection:Port=5672
      - RabbitMqSection:Queue=windpark
      - RabbitMqSection:RoutingKey=windpark
      - Logging:LogLevel:Default=Trace
      - Logging:LogLevel:System=Information
      - Logging:LogLevel:Microsoft=Information
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 100m
        mode: non-blocking

  windparkapiconsumer:
    image: windparkapiconsumer:latest
    depends_on:
      - rabbitmq
      - sqlserver
    environment:     
      - RabbitMqSection:HostName=rabbitmq
      - RabbitMqSection:Port=5672
      - RabbitMqSection:Queue=windpark
      - RabbitMqSection:RoutingKey=windpark   
      - Logging:LogLevel:Default=Information
      - Logging:LogLevel:System=Information
      - Logging:LogLevel:Microsoft=Information
    