// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindparkAPIAggregation.Repository;

#nullable disable

namespace WindparkAPIAggregation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WindparkAPIAggregation.Contracts.Turbine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CurrentProduction")
                        .HasColumnType("float");

                    b.Property<int>("TurbineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WindParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("WindParkId");

                    b.ToTable("Turbine");
                });

            modelBuilder.Entity("WindparkAPIAggregation.Contracts.WindPark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WindParkId");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("WindParkNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WindPark");
                });

            modelBuilder.Entity("WindparkAPIAggregation.Contracts.Turbine", b =>
                {
                    b.HasOne("WindparkAPIAggregation.Contracts.WindPark", "WindPark")
                        .WithMany("Turbines")
                        .HasForeignKey("WindParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WindPark");
                });

            modelBuilder.Entity("WindparkAPIAggregation.Contracts.WindPark", b =>
                {
                    b.Navigation("Turbines");
                });
#pragma warning restore 612, 618
        }
    }
}
