version: "3"

services: 
  rabbitmq:
    image: rabbitmq:3
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  interflex:
    image: windparkdemo:latest
    depends_on:
      - rabbitmq
    ports:
      - 3001:3001